<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatNacionalidadesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('cat_nacionalidades')->upsert([
            ['id' => 1, 'nombre' => 'Afgana'],
            ['id' => 2, 'nombre' => 'Albanesa'],
            ['id' => 3, 'nombre' => 'Alemana'],
            ['id' => 4, 'nombre' => 'Andorrana'],
            ['id' => 5, 'nombre' => 'Angoleña'],
            ['id' => 6, 'nombre' => 'Antiguana'],
            ['id' => 7, 'nombre' => 'Saudita'],
            ['id' => 8, 'nombre' => 'Argelina'],
            ['id' => 9, 'nombre' => 'Argentina'],
            ['id' => 10, 'nombre' => 'Armenia'],
            ['id' => 11, 'nombre' => 'Australiana'],
            ['id' => 12, 'nombre' => 'Austriaca'],
            ['id' => 13, 'nombre' => 'Azerbaiyana'],
            ['id' => 14, 'nombre' => 'Bahameña'],
            ['id' => 15, 'nombre' => 'Bangladesí'],
            ['id' => 16, 'nombre' => 'Barbadense'],
            ['id' => 17, 'nombre' => 'Bareiní'],
            ['id' => 18, 'nombre' => 'Belga'],
            ['id' => 19, 'nombre' => 'Beliceña'],
            ['id' => 20, 'nombre' => 'Beninesa'],
            ['id' => 21, 'nombre' => 'Bielorrusa'],
            ['id' => 22, 'nombre' => 'Birmana'],
            ['id' => 23, 'nombre' => 'Boliviana'],
            ['id' => 24, 'nombre' => 'Bosnia'],
            ['id' => 25, 'nombre' => 'Botsuana'],
            ['id' => 26, 'nombre' => 'Brasileña'],
            ['id' => 27, 'nombre' => 'Bruneana'],
            ['id' => 28, 'nombre' => 'Búlgara'],
            ['id' => 29, 'nombre' => 'Burkinesa'],
            ['id' => 30, 'nombre' => 'Burundesa'],
            ['id' => 31, 'nombre' => 'Butanesa'],
            ['id' => 32, 'nombre' => 'Caboverdiana'],
            ['id' => 33, 'nombre' => 'Camboyana'],
            ['id' => 34, 'nombre' => 'Camerunesa'],
            ['id' => 35, 'nombre' => 'Canadiense'],
            ['id' => 36, 'nombre' => 'Catarí'],
            ['id' => 37, 'nombre' => 'Chadiana'],
            ['id' => 38, 'nombre' => 'Chilena'],
            ['id' => 39, 'nombre' => 'China'],
            ['id' => 40, 'nombre' => 'Chipriota'],
            ['id' => 41, 'nombre' => 'Colombiana'],
            ['id' => 42, 'nombre' => 'Comorense'],
            ['id' => 43, 'nombre' => 'Congoleña'],
            ['id' => 44, 'nombre' => 'Norcoreana'],
            ['id' => 45, 'nombre' => 'Surcoreana'],
            ['id' => 46, 'nombre' => 'Costarricense'],
            ['id' => 47, 'nombre' => 'Marfileña'],
            ['id' => 48, 'nombre' => 'Croata'],
            ['id' => 49, 'nombre' => 'Cubana'],
            ['id' => 50, 'nombre' => 'Danesa'],
            ['id' => 51, 'nombre' => 'Dominicana'],
            ['id' => 52, 'nombre' => 'Ecuatoriana'],
            ['id' => 53, 'nombre' => 'Egipcia'],
            ['id' => 54, 'nombre' => 'Salvadoreña'],
            ['id' => 55, 'nombre' => 'Emiratí'],
            ['id' => 56, 'nombre' => 'Española'],
            ['id' => 57, 'nombre' => 'Estadounidense'],
            ['id' => 58, 'nombre' => 'Estonia'],
            ['id' => 59, 'nombre' => 'Etíope'],
            ['id' => 60, 'nombre' => 'Filipina'],
            ['id' => 61, 'nombre' => 'Finlandesa'],
            ['id' => 62, 'nombre' => 'Francesa'],
            ['id' => 63, 'nombre' => 'Guatemalteca'],
            ['id' => 64, 'nombre' => 'Haitiana'],
            ['id' => 65, 'nombre' => 'Hondureña'],
            ['id' => 66, 'nombre' => 'Mexicana'],
            ['id' => 67, 'nombre' => 'Nicaragüense'],
            ['id' => 68, 'nombre' => 'Panameña'],
            ['id' => 69, 'nombre' => 'Paraguaya'],
            ['id' => 70, 'nombre' => 'Peruana'],
            ['id' => 71, 'nombre' => 'Puertorriqueña'],
            ['id' => 72, 'nombre' => 'Uruguaya'],
            ['id' => 73, 'nombre' => 'Venezolana'],
        ], ['id'], ['nombre']);
    }
}
