<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatPaisesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('cat_paises')->upsert([
            ['id' => 1, 'nombre' => 'Afganistán'],
            ['id' => 2, 'nombre' => 'Albania'],
            ['id' => 3, 'nombre' => 'Alemania'],
            ['id' => 4, 'nombre' => 'Andorra'],
            ['id' => 5, 'nombre' => 'Angola'],
            ['id' => 6, 'nombre' => 'Antigua y Barbuda'],
            ['id' => 7, 'nombre' => 'Arabia Saudita'],
            ['id' => 8, 'nombre' => 'Argelia'],
            ['id' => 9, 'nombre' => 'Argentina'],
            ['id' => 10, 'nombre' => 'Armenia'],
            ['id' => 11, 'nombre' => 'Australia'],
            ['id' => 12, 'nombre' => 'Austria'],
            ['id' => 13, 'nombre' => 'Azerbaiyán'],
            ['id' => 14, 'nombre' => 'Bahamas'],
            ['id' => 15, 'nombre' => 'Bangladés'],
            ['id' => 16, 'nombre' => 'Barbados'],
            ['id' => 17, 'nombre' => 'Baréin'],
            ['id' => 18, 'nombre' => 'Bélgica'],
            ['id' => 19, 'nombre' => 'Belice'],
            ['id' => 20, 'nombre' => 'Benín'],
            ['id' => 21, 'nombre' => 'Bielorrusia'],
            ['id' => 22, 'nombre' => 'Birmania'],
            ['id' => 23, 'nombre' => 'Bolivia'],
            ['id' => 24, 'nombre' => 'Bosnia y Herzegovina'],
            ['id' => 25, 'nombre' => 'Botsuana'],
            ['id' => 26, 'nombre' => 'Brasil'],
            ['id' => 27, 'nombre' => 'Brunéi'],
            ['id' => 28, 'nombre' => 'Bulgaria'],
            ['id' => 29, 'nombre' => 'Burkina Faso'],
            ['id' => 30, 'nombre' => 'Burundi'],
            ['id' => 31, 'nombre' => 'Bután'],
            ['id' => 32, 'nombre' => 'Cabo Verde'],
            ['id' => 33, 'nombre' => 'Camboya'],
            ['id' => 34, 'nombre' => 'Camerún'],
            ['id' => 35, 'nombre' => 'Canadá'],
            ['id' => 36, 'nombre' => 'Catar'],
            ['id' => 37, 'nombre' => 'Chad'],
            ['id' => 38, 'nombre' => 'Chile'],
            ['id' => 39, 'nombre' => 'China'],
            ['id' => 40, 'nombre' => 'Chipre'],
            ['id' => 41, 'nombre' => 'Colombia'],
            ['id' => 42, 'nombre' => 'Comoras'],
            ['id' => 43, 'nombre' => 'Congo'],
            ['id' => 44, 'nombre' => 'Corea del Norte'],
            ['id' => 45, 'nombre' => 'Corea del Sur'],
            ['id' => 46, 'nombre' => 'Costa Rica'],
            ['id' => 47, 'nombre' => 'Costa de Marfil'],
            ['id' => 48, 'nombre' => 'Croacia'],
            ['id' => 49, 'nombre' => 'Cuba'],
            ['id' => 50, 'nombre' => 'Dinamarca'],
            ['id' => 51, 'nombre' => 'Dominica'],
            ['id' => 52, 'nombre' => 'Ecuador'],
            ['id' => 53, 'nombre' => 'Egipto'],
            ['id' => 54, 'nombre' => 'El Salvador'],
            ['id' => 55, 'nombre' => 'Emiratos Árabes Unidos'],
            ['id' => 56, 'nombre' => 'Eritrea'],
            ['id' => 57, 'nombre' => 'Eslovaquia'],
            ['id' => 58, 'nombre' => 'Eslovenia'],
            ['id' => 59, 'nombre' => 'España'],
            ['id' => 60, 'nombre' => 'Estados Unidos'],
            ['id' => 61, 'nombre' => 'Estonia'],
            ['id' => 62, 'nombre' => 'Etiopía'],
            ['id' => 63, 'nombre' => 'Filipinas'],
            ['id' => 64, 'nombre' => 'Finlandia'],
            ['id' => 65, 'nombre' => 'Francia'],
            ['id' => 66, 'nombre' => 'Gabón'],
            ['id' => 67, 'nombre' => 'Gambia'],
            ['id' => 68, 'nombre' => 'Georgia'],
            ['id' => 69, 'nombre' => 'Ghana'],
            ['id' => 70, 'nombre' => 'Granada'],
            ['id' => 71, 'nombre' => 'Grecia'],
            ['id' => 72, 'nombre' => 'Guatemala'],
            ['id' => 73, 'nombre' => 'Guinea'],
            ['id' => 74, 'nombre' => 'Guinea Ecuatorial'],
            ['id' => 75, 'nombre' => 'Guinea-Bisáu'],
            ['id' => 76, 'nombre' => 'Guyana'],
            ['id' => 77, 'nombre' => 'Haití'],
            ['id' => 78, 'nombre' => 'Honduras'],
            ['id' => 79, 'nombre' => 'Hungría'],
            ['id' => 80, 'nombre' => 'India'],
            ['id' => 81, 'nombre' => 'Indonesia'],
            ['id' => 82, 'nombre' => 'Irak'],
            ['id' => 83, 'nombre' => 'Irán'],
            ['id' => 84, 'nombre' => 'Irlanda'],
            ['id' => 85, 'nombre' => 'Islandia'],
            ['id' => 86, 'nombre' => 'Israel'],
            ['id' => 87, 'nombre' => 'Italia'],
            ['id' => 88, 'nombre' => 'Jamaica'],
            ['id' => 89, 'nombre' => 'Japón'],
            ['id' => 90, 'nombre' => 'Jordania'],
            ['id' => 91, 'nombre' => 'Kazajistán'],
            ['id' => 92, 'nombre' => 'Kenia'],
            ['id' => 93, 'nombre' => 'Kirguistán'],
            ['id' => 94, 'nombre' => 'Kiribati'],
            ['id' => 95, 'nombre' => 'Kuwait'],
            ['id' => 96, 'nombre' => 'Laos'],
            ['id' => 97, 'nombre' => 'Lesoto'],
            ['id' => 98, 'nombre' => 'Letonia'],
            ['id' => 99, 'nombre' => 'Líbano'],
            ['id' => 100, 'nombre' => 'Liberia'],
            ['id' => 101, 'nombre' => 'Libia'],
            ['id' => 102, 'nombre' => 'Liechtenstein'],
            ['id' => 103, 'nombre' => 'Lituania'],
            ['id' => 104, 'nombre' => 'Luxemburgo'],
            ['id' => 105, 'nombre' => 'Madagascar'],
            ['id' => 106, 'nombre' => 'Malasia'],
            ['id' => 107, 'nombre' => 'Malaui'],
            ['id' => 108, 'nombre' => 'Maldivas'],
            ['id' => 109, 'nombre' => 'Malí'],
            ['id' => 110, 'nombre' => 'Malta'],
            ['id' => 111, 'nombre' => 'Marruecos'],
            ['id' => 112, 'nombre' => 'Mauricio'],
            ['id' => 113, 'nombre' => 'Mauritania'],
            ['id' => 114, 'nombre' => 'México'],
            ['id' => 115, 'nombre' => 'Micronesia'],
            ['id' => 116, 'nombre' => 'Moldavia'],
            ['id' => 117, 'nombre' => 'Mónaco'],
            ['id' => 118, 'nombre' => 'Mongolia'],
            ['id' => 119, 'nombre' => 'Montenegro'],
            ['id' => 120, 'nombre' => 'Mozambique'],
            ['id' => 121, 'nombre' => 'Namibia'],
            ['id' => 122, 'nombre' => 'Nauru'],
            ['id' => 123, 'nombre' => 'Nepal'],
            ['id' => 124, 'nombre' => 'Nicaragua'],
            ['id' => 125, 'nombre' => 'Níger'],
            ['id' => 126, 'nombre' => 'Nigeria'],
            ['id' => 127, 'nombre' => 'Noruega'],
            ['id' => 128, 'nombre' => 'Nueva Zelanda'],
            ['id' => 129, 'nombre' => 'Omán'],
            ['id' => 130, 'nombre' => 'Países Bajos'],
            ['id' => 131, 'nombre' => 'Pakistán'],
            ['id' => 132, 'nombre' => 'Panamá'],
            ['id' => 133, 'nombre' => 'Papúa Nueva Guinea'],
            ['id' => 134, 'nombre' => 'Paraguay'],
            ['id' => 135, 'nombre' => 'Perú'],
            ['id' => 136, 'nombre' => 'Polonia'],
            ['id' => 137, 'nombre' => 'Portugal'],
            ['id' => 138, 'nombre' => 'Reino Unido'],
            ['id' => 139, 'nombre' => 'República Centroafricana'],
            ['id' => 140, 'nombre' => 'República Checa'],
            ['id' => 141, 'nombre' => 'República Dominicana'],
            ['id' => 142, 'nombre' => 'Ruanda'],
            ['id' => 143, 'nombre' => 'Rumanía'],
            ['id' => 144, 'nombre' => 'Rusia'],
            ['id' => 145, 'nombre' => 'Samoa'],
            ['id' => 146, 'nombre' => 'San Cristóbal y Nieves'],
            ['id' => 147, 'nombre' => 'San Marino'],
            ['id' => 148, 'nombre' => 'San Vicente y las Granadinas'],
            ['id' => 149, 'nombre' => 'Santa Lucía'],
            ['id' => 150, 'nombre' => 'Santo Tomé y Príncipe'],
            ['id' => 151, 'nombre' => 'Senegal'],
            ['id' => 152, 'nombre' => 'Serbia'],
            ['id' => 153, 'nombre' => 'Seychelles'],
            ['id' => 154, 'nombre' => 'Sierra Leona'],
            ['id' => 155, 'nombre' => 'Singapur'],
            ['id' => 156, 'nombre' => 'Siria'],
            ['id' => 157, 'nombre' => 'Somalia'],
            ['id' => 158, 'nombre' => 'Sri Lanka'],
            ['id' => 159, 'nombre' => 'Sudáfrica'],
            ['id' => 160, 'nombre' => 'Sudán'],
            ['id' => 161, 'nombre' => 'Sudán del Sur'],
            ['id' => 162, 'nombre' => 'Suecia'],
            ['id' => 163, 'nombre' => 'Suiza'],
            ['id' => 164, 'nombre' => 'Surinam'],
            ['id' => 165, 'nombre' => 'Tailandia'],
            ['id' => 166, 'nombre' => 'Tanzania'],
            ['id' => 167, 'nombre' => 'Tayikistán'],
            ['id' => 168, 'nombre' => 'Timor Oriental'],
            ['id' => 169, 'nombre' => 'Togo'],
            ['id' => 170, 'nombre' => 'Tonga'],
            ['id' => 171, 'nombre' => 'Trinidad y Tobago'],
            ['id' => 172, 'nombre' => 'Túnez'],
            ['id' => 173, 'nombre' => 'Turkmenistán'],
            ['id' => 174, 'nombre' => 'Turquía'],
            ['id' => 175, 'nombre' => 'Tuvalu'],
            ['id' => 176, 'nombre' => 'Ucrania'],
            ['id' => 177, 'nombre' => 'Uganda'],
            ['id' => 178, 'nombre' => 'Uruguay'],
            ['id' => 179, 'nombre' => 'Uzbekistán'],
            ['id' => 180, 'nombre' => 'Vanuatu'],
            ['id' => 181, 'nombre' => 'Vaticano'],
            ['id' => 182, 'nombre' => 'Venezuela'],
            ['id' => 183, 'nombre' => 'Vietnam'],
            ['id' => 184, 'nombre' => 'Yemen'],
            ['id' => 185, 'nombre' => 'Yibuti'],
            ['id' => 186, 'nombre' => 'Zambia'],
            ['id' => 187, 'nombre' => 'Zimbabue'],
        ], ['id'], ['nombre']);
    }
}
